language: python

sudo: false

env:
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.2"
    - LUA="lua 5.3"

before_install:
  - pip install hererocks
  - hererocks ~/hererocks -r^ --$LUA
  - export PATH=$PATH:~/hererocks/bin
  - eval `luarocks path --bin`
  - export LUA_PATH="$LUA_PATH"';./?.lua;./?/init.lua'
  - luarocks install luacheck
  - luarocks install busted

install:
  - luarocks make
  - find . -type d

script:
  - luacheck . --no-color --codes --exclude-files spec/out
  - busted -o plainTerminal

cache:
  directories:
    - $HOME/.cache/hererocks
