-- luacheck: ignore
file = {'bin', 'fusion'} -- vim:set noet sts=0 sw=3 ts=3 filetype=lua:
dir = 'docs'
project = 'FusionScript'
description = 'The programming language of ultimate dankliness'
title = 'FusionScript &middot; Documentation'
style = 'docs/style'
topics = {
	'.topics/FusionScript.md';
	'.topics/Syntax.md';
}
kind_names = {topic='Manual', script='Programs'}
all = true
format = 'markdown'
