local ternary = require("fusion.stdlib.ternary")

describe("ternary", function()
	it("can calculate simple ternary operations", function()
		assert.same(true, ternary(true, true, false))
		assert.same(true, ternary(1, true, false))
		assert.same(0, ternary(false, true, 0))
		assert.same(nil, ternary(true, nil, false))
		assert.same(false, ternary(true, false, nil))
	end)
	it("can calculate nested ternary operations", function()
		assert.same(true, ternary(true, ternary(false, 0, true), nil))
		assert.same(false, ternary(nil, ternary(true, "hi", "test"), false))
		assert.same(1, ternary(ternary(false, nil, true), 1, 0))
	end)
end)
